### ISSUE TITLE
Warning: React.createClass is deprecated

### ISSUE THREAD

**Issue by rakeshpai** [glennflanagan/react-collapsible#24]
Just installed this module, and got the following error in the console.

> Warning: Collapsible: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

**Comment by negomi** [comment]
Also:
```
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
```

**Comment by glennflanagan** [comment]
@rakeshpai @negomi this is down to Facebook releasing v15.5 of React. There has been a PR into develop which fixes this, but I won't be releasing this until v2.0

**Comment by michaelsbradleyjr** [comment]
I started using your component in the context of a [next.js](https://github.com/zeit/next.js) app and decided to rework the code such that its up-to-date and takes advantage of the babel presets available in that framework's `dev` workflow.

Here's the result: https://gist.github.com/michaelsbradleyjr/ea26c9789e633413df727d38a353db5e

I can submit a proper pull request, but I'd need to figure out how exactly to setup babel/webpack correctly so that all of the ES2017 features work, tests pass, etc. Let me know what you think.

**Comment by jerronl** [comment]
do we have a solution yet? will it work with react v16?

**Comment by alexmcmillan** [comment]
+1
