### ISSUE TITLE
lazyRender doesn't work without css

### ISSUE THREAD

**Issue by jmckib** [glennflanagan/react-collapsible#36]
If you use `lazyRender` without css, then panel doesn't unfold until there have been three clicks. I believe this is because the height of the children is unknown until the first render, so the first click renders the children (but doesn't unfold because height is 0), the second click closes, then the third click finally unfolds correctly.

To reproduce this, delete the content of `example/_src/sass/components/_Collapsible.scss`, open the example and click on "What happens if there's a shed-load of content?" It should take three clicks to open properly.

If this isn't going to be changed, the documentation should indicate that some css is required for `lazyRender` to work.

**Comment by jmckib** [comment]
Just noticed this is addressed by https://github.com/glennflanagan/react-collapsible/pull/22

**Comment by mrTurkay** [comment]
Hello, I have exactly same issue, and I need to solve it. 

I tried some css but it still haven't worked yet. What kind css should I apply it?

**Comment by jmckib** [comment]
@mrTurkay I'm not sure which exact lines of css are necessary, but you can copy the css being used in the collapsible example and it should work.

**Comment by glennflanagan** [comment]
I've implemented the fix from #22 into the develop branch. I should be releasing it as part of v2.0 soon.

**Comment by Victor-Ross** [comment]
For anyone having trouble with this broken lib, that has gone years and havent seen a fix for this problem.
1° option:
use contentInnerClassName and put a transparent border on it.

2° option:
use the built in classes ofered by the lib, like the following example:

.Collapsible__contentInner {
  border: 1px solid transparent;
}

**Comment by glennflanagan** [comment]
@Victor-Ross what exactly is broken? Did you open PR to fix this free software?

**Comment by tahini** [comment]
We're also facing this issue. We recently upgraded from 2.8 to 2.10 and the Collapsible that were lazyRender'ed were not opening on first click anymore.

To reproduce, remove the `Collapsible__contentInner` style from the _Collapsible.scss and try opening the lazyRendered element in the example. In our project, we just added a 1px padding on top and it works now. We didn't need it with the 2.8.0 library.

Unfortunately, I get build errors when compiling the 2.8.0 version so I can't properly bisect and see where the bug comes from.
